# ruff: noqa: F401
from .abstract import TUDataModule
from .classification import (
    AdultCensusIncomeDataModule,
    AmazonAccessDataModule,
    APSFailureDataModule,
    BankMarketingDataModule,
    CIFAR10DataModule,
    CIFAR100DataModule,
    CreditApprovalDataModule,
    DOTA2GamesDataModule,
    GermanCreditDataModule,
    HiggsBosonDataModule,
    HTRU2DataModule,
    ImageNet200DataModule,
    ImageNetDataModule,
    KDDChurnDataModule,
    MNISTDataModule,
    OnlineShoppersDataModule,
    PimaDiabetesDataModule,
    SpamBaseDataModule,
    TabularClassificationDataModule,
    TelcoChurnDataModule,
    TinyImageNetDataModule,
    UCRUEADataModule,
    WineQualityDataModule,
)
from .segmentation import CamVidDataModule, CityscapesDataModule, MUADDataModule
from .tabular_regression import (
    BostonHousingDataModule,
    ConcreteDataModule,
    EnergyEfficiencyDataModule,
    EnergyPredictionDataModule,
    Kin8NMDataModule,
    NavalPropulsionPlantDataModule,
    PowerPlantDataModule,
    ProteinDataModule,
    TabularRegressionDataModule,
    WineQualityRegressionDataModule,
    YachtDataModule,
)
