name: Docs

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"
  # Fetch the branch name from the workflow that triggered this one, fallback to ref_name
  BRANCH_NAME: ${{ github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  documentation:
    # Run if triggered manually OR if the "Tests" workflow succeeded, wasn't dependabot, 
    # and targeted the main branch (either via push or PR).
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.workflow_run.conclusion == 'success' &&
        !contains(github.event.workflow_run.head_branch, 'dependabot') &&
        (
          github.event.workflow_run.event == 'push' || 
          (github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].base.ref == 'main')
        )
      )
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Check if PR is draft
        id: check_draft
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ "${{ github.event.workflow_run.event }}" == "pull_request" ]; then
            BRANCH="${{ github.event.workflow_run.head_branch }}"

            PR_NUMBER=$(gh pr list \
              --repo ${{ github.repository }} \
              --head "$BRANCH" \
              --json number \
              --jq '.[0].number')

            if [ -z "$PR_NUMBER" ]; then
              echo "No PR found for branch $BRANCH"
              echo "is_draft=false" >> $GITHUB_OUTPUT
              exit 0
            fi

            IS_DRAFT=$(gh pr view $PR_NUMBER \
              --repo ${{ github.repository }} \
              --json isDraft \
              --jq '.isDraft')

            echo "is_draft=$IS_DRAFT" >> $GITHUB_OUTPUT
          else
            echo "is_draft=false" >> $GITHUB_OUTPUT
          fi
          echo "BRANCH=$BRANCH"
          echo "PR_NUMBER=$PR_NUMBER"
          echo "IS_DRAFT=$IS_DRAFT"

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.0"
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: "true"

      - name: Full Python version
        run: |
          echo "PYTHON_VERSION=$(python -c "import platform; print(platform.python_version())")"

      # - name: Cache folder for TorchUncertainty
      #   uses: actions/cache@v4
      #   id: cache-folder
      #   with:
      #     path: |
      #       auto_tutorial_source
      #       docs
      #     key: torch-uncertainty-${{ runner.os }}-${{ env.BRANCH_NAME }}

      - name: Install dependencies
        run: |
          uv sync --locked --dev --extra gpu

      - name: Sphinx build
        if: steps.check_draft.outputs.is_draft != 'true'
        run: |
          cd docs && make html

      - name: Deploy on GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        if: >
          github.event_name == 'workflow_dispatch' || 
          (github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main')
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: torch-uncertainty/torch-uncertainty.github.io
          publish_branch: main
          publish_dir: docs/build/html
        continue-on-error: true

      # ||: not to error if there is no running ssh-agent
      - name: Kill SSH Agent
        run: |
          killall ssh-agent ||:
