name: Tests

env:
  UV_NO_SYNC: true

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  schedule:
    - cron: "42 7 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.0"
          python-version: ${{ matrix.python-version }}
          enable-cache: "true"

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v47
        with:
          files: |
            auto_tutorials_source/**
            data/**
            experiments/**
            docs/**
            *.md
            *.yaml
            *.yml
            LICENSE
            .gitignore
      
      - name: Check previous commit workflow result
        id: prev
        run: |
          result=$(gh api \
            repos/${{ github.repository }}/commits/${{ github.event.before }}/check-runs \
            --jq '.check_runs[] | select(.name=="Tests") | .conclusion' \
            | head -n1)

          echo "result=$result" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Last result
        run: |
          echo $GITHUB_OUTPUT

      - name: Fail if previous tests failed and nothing important changed
        if: |
          steps.prev.outputs.result == 'failure' &&
          steps.changed-files-specific.outputs.only_changed != 'true' &&
          github.event_name != 'workflow_dispatch' &&
          github.event.before != ''
        run: |
          echo "Previous tests failed and no important files changed."
          exit 1

      - name: Decide test mode
        id: mode
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "mode=full" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.changed-files-specific.outputs.only_changed }}" != "true" ]]; then
            echo "mode=full" >> $GITHUB_OUTPUT
          else
            echo "mode=minimal" >> $GITHUB_OUTPUT
          fi

      - name: Install the project
        if: steps.mode.outputs.mode == 'full'
        run: uv sync --locked --dev --extra cpu

      - name: Check that torch-uncertainty can be imported
        if: steps.mode.outputs.mode == 'full'
        run: |
          uv run python -c "import torch_uncertainty; from torch_uncertainty.datamodules import MNISTDataModule"

      - name: Check style & format
        if: steps.mode.outputs.mode == 'full'
        run: |
          uv run ruff check src/torch_uncertainty --no-fix --statistics
          uv run ruff format src/torch_uncertainty --check

      - name: Test with pytest and compute coverage
        if: steps.mode.outputs.mode == 'full'
        run: |
          uv run --frozen pytest tests --cov --cov-report xml --cov-report term --durations 10 --junitxml=junit.xml

      # Store Python version
      - name: Full Python version
        run: |
          echo "PYTHON_VERSION=$(uv run python -c "import platform; print(platform.python_version())")" >> $GITHUB_ENV

      - name: Upload coverage to Codecov
        if: steps.mode.outputs.mode == 'full' && (github.event_name != 'pull_request' || github.base_ref == 'dev')
        uses: codecov/codecov-action@v4
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: pytest
          name: CPU-coverage
          env_vars: PYTHON_VERSION

      - name: Upload test results to Codecov
        if: steps.mode.outputs.mode == 'full' && (github.event_name != 'pull_request' || github.base_ref == 'dev')
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: pytest
          env_vars: PYTHON_VERSION
          report_type: test_results

      - name: Test sphinx build without tutorials
        if: steps.mode.outputs.mode == 'full'
        run: |
          cd docs && make clean && make html-noplot
